version: '3.7'
services:
  qgis-server:
    #image: opengisch/qgis-server-standalone:latest
    environment:
      # Limit the maximum size returned by a GetMap
      QGIS_SERVER_WMS_MAX_HEIGHT: 5000
      QGIS_SERVER_WMS_MAX_WIDTH: 5000
      QGIS_SERVER_IGNORE_BAD_LAYERS: 1
    volumes:
      - ./projects:/io/data:ro
      # use default PG location so there is no need define it as fcgi_param
      - ./conf/pg_service.conf:/etc/postgresql-common/pg_service.conf:ro
      #- ./conf/fonts:/usr/local/share/fonts:ro
      #- ./projects/svg:/var/lib/qgis/.local/share/QGIS/QGIS3/profiles/default/svg:ro
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - 8001:80
    networks:
      - net
    command: >
      bash -c "/usr/bin/xvfb-run -a /usr/bin/qgis_mapserver -l 0 localhost:80"
    depends_on:
      - postgis

  postgis:
    image: kartoza/postgis:11.5-2.8
    restart: always
    volumes:
      - postgis-data:/var/lib/postgresql
    ports:
      - 54321:5432
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 50501:80
    volumes:
      - ../conf/pg/pg_service.conf:/pgadmin4/.pg_service.conf
    environment:
      PGADMIN_DEFAULT_EMAIL: play@opengis.ch
      PGADMIN_DEFAULT_PASSWORD: ciao
      PGSERVICEFILE: /pgadmin4/.pg_service.conf
    networks:
      - net
    depends_on:
      - postgis

volumes:
  postgis-data:

networks:
  net: