name: Docker image

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  docker-tests:
    name: Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "build dockerfile"
        run: docker build --tag opengisch/qgis-server-standalone .

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Push to dockerhub"
        if: github.event_name != 'pull_request'
        run: |
          docker push pengisch/qgis-server-standalone:latest
